const historial = [
    {
        id: '1',
        fecha: '17-ENE-2024 10:57:09',
        usuario: 'Laura Martínez',
        producto: 'Notebook T-14',
        accion: 'Borrado',
    },
    {
        id: '2',
        fecha: '05-FEB-2024 14:23:45',
        usuario: 'Carlos Ramírez',
        producto: 'Impresora HP DeskJet',
        accion: 'Borrado',
    },
    {
        id: '3',
        fecha: '23-MAR-2024 09:15:32',
        usuario: 'Ana González',
        producto: 'Router TP-Link',
        accion: 'Borrado',
    },
    {
        id: '4',
        fecha: '11-ABR-2024 17:42:18',
        usuario: 'Pedro Hernández',
        producto: 'Monitor Samsung',
        accion: 'Borrado',
    },
    {
        id: '5',
        fecha: '29-MAY-2024 11:01:55',
        usuario: 'María Fernández',
        producto: 'Teclado Mecánico',
        accion: 'Borrado',
    },
    {
        id: '6',
        fecha: '07-JUN-2024 08:22:44',
        usuario: 'Luis García',
        producto: 'Disco Duro Externo',
        accion: 'Exportado',
    },
    {
        id: '7',
        fecha: '19-JUL-2024 13:14:30',
        usuario: 'Elena Castillo',
        producto: 'Tarjeta Gráfica RTX 3080',
        accion: 'Exportado',
    },
    {
        id: '8',
        fecha: '10-AGO-2024 16:29:11',
        usuario: 'Fernando Morales',
        producto: 'Laptop Dell XPS 13',
        accion: 'Exportado',
    },
    {
        id: '9',
        fecha: '02-MAR-2024 07:05:27',
        usuario: 'Sofía Sánchez',
        producto: 'Mouse Logitech G502',
        accion: 'Importado',
    },
    {
        id: '10',
        fecha: '15-ABR-2024 12:46:38',
        usuario: 'Miguel Torres',
        producto: 'Tablet Samsung Galaxy',
        accion: 'Modificado',
    },
    {
        id: '11',
        fecha: '04-JUN-2024 14:17:55',
        usuario: 'Gabriela López',
        producto: 'Auriculares Bose QC35',
        accion: 'Importado',
    },
    {
        id: '12',
        fecha: '21-MAY-2024 09:32:41',
        usuario: 'Javier Núñez',
        producto: 'Smartwatch Apple Watch',
        accion: 'Exportado',
    },
    {
        id: '13',
        fecha: '13-FEB-2024 16:45:20',
        usuario: 'Paula Díaz',
        producto: 'Cámara Nikon D3500',
        accion: 'Modificado',
    },
    {
        id: '14',
        fecha: '26-JUL-2024 10:55:08',
        usuario: 'Roberto Silva',
        producto: 'Consola PS5',
        accion: 'Importado',
    },
    {
        id: '15',
        fecha: '09-ENE-2024 11:18:36',
        usuario: 'Mónica Reyes',
        producto: 'Smartphone OnePlus 9',
        accion: 'Exportado',
    },
    {
        id: '16',
        fecha: '18-FEB-2024 15:24:14',
        usuario: 'Andrés Gutiérrez',
        producto: 'Proyector Epson',
        accion: 'Creacion',
    },
    {
        id: '17',
        fecha: '12-MAR-2024 13:08:22',
        usuario: 'Patricia Vega',
        producto: 'Switch Cisco',
        accion: 'Importado',
    },
    {
        id: '18',
        fecha: '30-ABR-2024 09:59:33',
        usuario: 'Tomás Castro',
        producto: 'Laptop Lenovo ThinkPad',
        accion: 'Creacion',
    },
    {
        id: '19',
        fecha: '15-AGO-2024 14:21:57',
        usuario: 'Beatriz Jiménez',
        producto: 'Disco SSD Samsung',
        accion: 'Creacion',
    },
    {
        id: '20',
        fecha: '22-JUN-2024 10:34:12',
        usuario: 'Diego Vargas',
        producto: 'Monitor LG UltraWide',
        accion: 'Creacion',
    },
];

export default historial;
